### ISSUE TITLE
mac support

### ISSUE THREAD

**Issue by twiggy** [appoptics/appoptics-bindings-node#3]
Is mac support anywhere on the roadmap? 

many developers use mac locally and if appoptics has an error they don't know till its deployed to a testing env.

linux vm is an option, but not a preferred one.

thanks again

**Comment by cheempz** [comment]
OS X support is something on our radar, enough so that we've allowed the "no-op" mode as a first step.

As you pointed out, it doesn't help unearth agent issues.  So far we've relied on running docker or a VM   (some of us develop on Macs too) so it hasn't been top of our list to add operational support for OS X.  But I will log this in our internal system as a data point for product features.  Thanks again for being such an enthusiastic user :)
